---
title: "consommation"
author: "Insee Bretagne LA"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE,message = FALSE)


# Lecture du fichier requirements.txt
requirements <- readLines("requirements_R.txt")

# Installation des packages
for (package in requirements) {
  install.packages(package)
}


library(aws.s3)
library(dplyr)
library(readr)

bucket <- "projet-funathon"
path_data <- "2023/sujet3/diffusion"

description_indiv <- s3read_using(read_delim, object = paste(path_data, "description-indiv.csv", sep="/"), bucket = bucket, opts = list('region'=''), show_col_types = FALSE)
habitudes_indiv <- s3read_using(read_delim, object = paste(path_data, "habitudes-indiv.csv", sep="/"), bucket = bucket, opts = list('region'=''), show_col_types = FALSE)
actphys_sedent <- s3read_using(read_delim, object = paste(path_data, "actphys-sedent.csv", sep="/"), bucket = bucket, opts = list('region'=''), show_col_types = FALSE)
fpq <- s3read_using(read_delim, object = paste(path_data, "fpq.csv", sep="/"), bucket = bucket, opts = list('region'=''), show_col_types = FALSE)



library(ggplot2)
library(ggcorrplot)
library(sf)

library(FactoMineR)
library(haven)
library(factoextra)
library(corrplot)

library(kableExtra)

```


##ACP

```{r}


## partie ACP


# classif

habitudes_indiv_clustering_1 <- habitudes_indiv %>%
  select(-c(POPULATION, NOIND, periode_reference)) %>%  # Identifiants
  select_if(function(col) any(!is.na(col))) %>%  # Colonnes vides
  select_if(is.numeric) %>%  # Colonnes numériques à garder
  select_if(function(col) length(unique(col)) > 1) 


Mode <- function(x) {
  non_missing_values <- x[!is.na(x)]
  ux <- unique(non_missing_values)
  ux[which.max(tabulate(match(non_missing_values, ux)))]
}

clustering_2 <- habitudes_indiv_clustering_1 %>%
  mutate_all(~ifelse(is.na(.), Mode(.), .)) %>%
  select_if(function(col) length(unique(col)) > 1)

## réalisation de l'ACP

acp2 <- PCA(clustering_2, graph=F,ncp=4)


fviz_screeplot(acp2, ncp=10)
## remarque : a priori l'information se trouve sur les 3 premiers axes.
## on peut laisser 5 (ncp par défaut)

fviz_pca_var(acp2, col.var="contrib",
             cex = 0.3,
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             select.var=list(contrib = 15))

fviz_pca_var(acp2, col.var="contrib",
             axes = c(3,4),
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             select.var=list(contrib = 15))




# Contributions des variables à PC1
fviz_contrib(acp2, choice = "var", axes = 1, top = 10)
# Contributions des variables à PC2
fviz_contrib(acp2, choice = "var", axes = 2, top = 10)
# Contributions des variables à PC3
fviz_contrib(acp2, choice = "var", axes = 3, top = 10)
# Contributions des variables à PC4
fviz_contrib(acp2, choice = "var", axes = 4, top = 10)



```

## CAH

```{r}


CAH2<-HCPC(acp2,graph=FALSE,nb.clust=5)

 plot(CAH2, choice="tree")

classe <-  as.data.frame(CAH2$data.clust$clust) 


desp<- bind_cols(clustering_2,classe) %>% rename(classe=`CAH2$data.clust$clust`)

table(desp$classe) 


## description des classes.
r <- CAH2$desc.var$quanti

r1 <- r$`1`
r2 <- r$`2`
r3 <- r$`3`
r4 <- r$`4`

r1 %>% kable(caption="classe 1")
r2 %>% kable(caption="classe 2")
r3 %>% kable(caption="classe 3")
r4 %>% kable(caption="classe 4")

```

